# Generated by Django 4.2.7 on 2024-01-10 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EcomApp', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('prod', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
